MockupForBusiness/Models/ErrorViewModel.cs
using System;

namespace MockupForBusiness.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MockupForBusiness/Models/QueueVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MockupForBusiness.Models
{
    public class QueueVm
    {
        public string EmailTo { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}

MockupForBusiness/Controllers/AzureController.cs
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Queue;
using MockupForBusiness.Models;
using Newtonsoft.Json;

namespace MockupForBusiness.Controllers
{
    public class AzureController : Controller
    {
        [HttpGet("blob-upload")]
        public IActionResult BlobUpload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FileUpload(IFormFile file)
        {
            var uri = await UploadFileToStorage(file.OpenReadStream(), file.FileName);

            return Ok(uri);
        }

        [HttpGet("azure-queue")]
        public IActionResult AzureQueue()
        {
            return View(new QueueVm());
        }

        [HttpPost("azure-queue")]
        public IActionResult AzureQueue(QueueVm model)
        {
                // Retrieve storage account from connection string.
                var storageAccount = CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=storageaccountsii98a7;AccountKey=MyX3i4pRFpQdipD4EOSxUQNEEk37L8OJ94nM0pqkKIDGYfY4JvRaDCmdCA5tc+3ElfNBZJVzPyLs8bX/s6RJXg==;EndpointSuffix=core.windows.net");
                // Create the queue client.
                var queueClient = storageAccount.CreateCloudQueueClient();
                // Retrieve a reference to a container.
                var queue = queueClient.GetQueueReference("myfirstqueue");
                // Create the queue if it doesn't already exist
                queue.CreateIfNotExistsAsync();

                var message = new CloudQueueMessage(JsonConvert.SerializeObject(model));
                queue.AddMessageAsync(message);

                return Content("Email wrzucony na kolejke");
        }

        public async Task<string> UploadFileToStorage(Stream stream, string uploadName)
        {
            var fileStream = stream;
            var fileName = uploadName;
            var accountName = "storageaccountsii98a7";
            var accountKey = "MyX3i4pRFpQdipD4EOSxUQNEEk37L8OJ94nM0pqkKIDGYfY4JvRaDCmdCA5tc+3ElfNBZJVzPyLs8bX/s6RJXg==";
            var imageCointainer = "testimagecontainar";


            // Create storagecredentials object by reading the values from the configuration (appsettings.json)
            var storageCredentials = new StorageCredentials(accountName, accountKey);

            // Create cloudstorage account by passing the storagecredentials
            var storageAccount = new CloudStorageAccount(storageCredentials, true);

            // Create the blob client.
            var blobClient = storageAccount.CreateCloudBlobClient();

            // Get reference to the blob container by passing the name by reading the value from the configuration (appsettings.json)
            var container = blobClient.GetContainerReference(imageCointainer);

            // Get the reference to the block blob from the container
            var blockBlob = container.GetBlockBlobReference(fileName);

            // Upload the file
            await blockBlob.UploadFromStreamAsync(fileStream);

            // return await Task.FromResult(true);
            return blockBlob.Uri.ToString();
        }
    }
}

MockupForBusiness/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MockupForBusiness.Models;

namespace MockupForBusiness.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IOfficeService _officeService;
        private readonly IWorkerService _workerService;
        private readonly IHobbyService _hobbyService;

        public HomeController(ILogger<HomeController> logger, IOfficeService officeService, IWorkerService workerService, IHobbyService hobbyService)
        {
            _logger = logger;
            _officeService = officeService;
            _workerService = workerService;
            _hobbyService = hobbyService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _officeService.GetOfficesListDtoAsync();
            return View(model);
        }

        [HttpGet("{city}", Name = "City")]
        public IActionResult OfficeWithWorkers(string city)
        {
            var model = _officeService.GetOfficesOfficeVms().FirstOrDefault(x => x.OfficeCity.Equals(city));

            var officeWithWorkers = _officeService.GetOfficeWithWorkersVm(model.OfficeId);
            return View(officeWithWorkers);
        }

        [HttpGet("json/{city}", Name = "JsonCity")]
        public IActionResult JsonOfficeWithWorkers(string city)
        {
            var model = _officeService.GetOfficesOfficeVms().FirstOrDefault(x => x.OfficeCity.Equals(city));

            var officeWithWorkers = _officeService.GetOfficeWithWorkersVm(model.OfficeId);
            return Json(officeWithWorkers);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

MockupForBusiness/Views/Azure/AzureQueue.cshtml
@{
    ViewData["Title"] = "Email to Queue";
}
@model QueueVm
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@using (Html.BeginForm("AzureQueue", "Azure", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.TextBoxFor(x => x.EmailTo, null, new { @class = "txt", placeholder = "Email" })

    @Html.TextBoxFor(x => x.Subject, null, new { @class = "txt", placeholder = "Subject" })

    @Html.TextBoxFor(x => x.Body, null, new { @class = "txt", placeholder = "Body" })

    <input type="submit" name="Submit" id="btnSubmit" value="Put Email to Queue" />
}

MockupForBusiness/Views/Azure/BlobUpload.cshtml
@{
    ViewData["Title"] = "Photo Upload";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@using (Html.BeginForm("FileUpload", "Azure", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" class="form-control" />
    <input type="submit" name="Submit" id="btnSubmit" value="Upload Files" />
}

MockupForBusiness/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<Infrastructure.Models.OfficeDto>

<div class="text-center">
    <div>
        <img src="/pic/Sii_logo.jpg" height="100px"/>
    </div>
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
@Html.ActionLink("Blob Upload", "BlobUpload", "Azure", null)
<br/>
<a href="/azure-queue">Azure Queue</a>

<br>
<br>

@foreach (var office in Model)
{
    <div>
        <a href="@office.OfficeCity">@office.OfficeName</a>
    </div>
}

MockupForBusiness/Views/Home/OfficeWithWorkers.cshtml
@model Infrastructure.Models.OfficeWithWorkersDto
@{
    ViewData["Title"] = "Office Page";
}

    <div><p>@Model.Office.OfficeName</p></div>

@foreach (var worker in Model.Office.Workers)
{
    <div><p>@worker.WorkerName @worker.WorkerSurname</p></div>
    
    <div>
        @foreach (var hobby in worker.Hobbies)
        {
        <p>@hobby.HobbyName</p>
        }
    </div>
}

<!-- HTML -->
<div id="chartdiv"></div>


<!-- Styles -->
<style>
    #chartdiv {
        height: 550px;
        width: 100%;
    }
</style>

<!-- Resources -->
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/plugins/forceDirected.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<script src="js/webinar.js"></script>

MockupForBusiness/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MockupForBusiness</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MockupForBusiness</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
</header>
<div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MockupForBusiness - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>